# Exported from Render on 2026-08-14T04:19:33Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: solar-system-api
      runtime: node
      repo: https://github.com/vodkashot-star/solar-system
      plan: free
      envVars:
      - key: DATABASE_URL
        sync: false
      - key: NODE_ENV
        sync: false
      - key: LOG_LEVEL
        sync: false
      - key: ALLOWED_ORIGIN
        sync: false
      - key: SPACEAI_URL
        sync: false
      region: oregon
      buildCommand: npm install --include=dev && npm run build
      startCommand: node dist/index-prod.js
      healthCheckPath: /api/health
      autoDeployTrigger: commit
    - type: web
      name: solar-system-ml
      runtime: python
      repo: https://github.com/vodkashot-star/solar-system
      plan: free
      region: oregon
      buildCommand: cd spaceAI && python -m venv venv && ./venv/bin/pip install -r
        requirements.txt
      startCommand: cd spaceAI && ./venv/bin/python run.py serve
      healthCheckPath: /health
      autoDeployTrigger: commit

